version: '3'
services:
  app:
    build:
      context: .
      args:
        VARIANT: 18-bullseye
    user: node
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ../:/workspaces/app
      # - pnpm_cached:/workspaces/app/.pnpm-store
    command: /bin/sh -c "while sleep infinity; do :; done"
# volumes:
#   pnpm_cached:
#     external: true
